image: node:16.14.0

cache:
  paths:
    - node_modules/

deploy_production:
  stage: deploy
  environment: Production
  script:
    - npm cache clean --force
    - npm install -g firebase-tools
    - npm install
    - npm run build
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY